import React, { useEffect } from "react";
import SectionHeader from "../Components/SectionHeader";

import Aos from "aos";
import "aos/dist/aos.css";

// Import Images
import animation from "../images/services/animation-img.svg";
import graphics from "../images/services/graphics-img.svg";
import motion from "../images/services/motion-graphics-img.svg";
import threeD from "../images/services/3D-modelling-img.svg";
import vfx from "../images/services/vfx-img.svg";
import gameDev from "../images/services/game-dev-img.svg";

// Service Components dynamically generated by passing in props
const Slide = () => {
  const slidesData = [
    {
      id: 1,
      name: "Animation",
      img: animation,
      description:
        "Our animators specialize in 2D and 3D animation and are experienced in creating both character and motion graphics animations. Our animation services include concept design, story boarding, character design, asset creation, and animation.",
    },
    {
      id: 2,
      name: "VFX",
      img: vfx,
      description:
        "Our VFX team has extensive experience in creating realistic and seamless visual effects for film, television, and commercials. Our services include green screen removal, compositing, 3D tracking, particle simulations, and digital matte painting Etc",
    },
    {
      id: 3,
      name: "Game Development",
      img: gameDev,
      description:
        "Our game development team creates immersive games for desktop, mobile, and consoles. We specialize in concept design, game design, and artwork creation. We use industry-standard tools such as Unity and Unreal Engine to develop games that meet client expectations. Our end-to-end game development services ensure high-quality and timely delivery of games.",
    },
    {
      id: 4,
      name: "Motion Design",
      img: motion,
      description:
        "Our motion graphics team specializes in creating animated graphics and typography for videos, presentations, and websites. Our services include concept design, story boarding, asset creation, animation, and sound design.",
    },
    {
      id: 5,
      name: "Graphics Design",
      img: graphics,
      description:
        "Our graphics design team specializes in creating high-quality and visually appealing designs for a wide range of applications, including branding, advertising, packaging, and digital media. We work closely with clients to bring their vision to life",
    },
    {
      id: 6,
      name: "3D Modelling",
      img: threeD,
      description:
        "Our 3D modeling team is highly skilled in creating realistic and detailed 3D models for film, television, and gaming industries. We offer services in character and prop modeling, environment and architectural visualization, and product design. Our team works closely with clients to deliver exceptional results.",
    },
  ];

  return slidesData.map((slide, reveal) => (
    <figure
      className={`flex flex-col md:w-[50%] overflow-hidden opacity-${reveal} items-center gap-[1.5rem] w-[100%]`}
    >
      <img src={slide.img} alt={slide.name} />
      <h3 className="font-bold text-3xl self-start">{slide.name}</h3>
      <p>{slide.description}</p>
    </figure>
  ));
};

// Each frame for the slider containing two components

// Service section component containing the 3 slider frames
const Services = () => {
  useEffect(() => {
    Aos.init();
  }, []);

  return (
    <section id="services" className="bg-elPurple w-auto">
      <SectionHeader
        color={"elLilac"}
        section={"SERVICES"}
        heading={"Our team is proficient in the following areas"}
        animate={"zoom-out"}
      />
      <div className="py-[10rem] flex px-[5rem] text-white">
        <Slide />
        {/* <Slide
          name="Animation"
          img={animation}
          description="Our animators specialize in 2D and 3D animation and are experienced in creating both character and motion graphics animations. Our animation services include concept design, story boarding, character design, asset creation, and animation."
        />
        <Slide
          name="VFX"
          img={vfx}
          description="Our VFX team has extensive experience in creating realistic and seamless visual effects for film, television, and commercials. Our services include green screen removal, compositing, 3D tracking, particle simulations, and digital matte painting Etc"
        />
        <Slide
          name="Game Development"
          img={gameDev}
          description="Our game development team creates immersive games for desktop, mobile, and consoles. We specialize in concept design, game design, and artwork creation. We use industry-standard tools such as Unity and Unreal Engine to develop games that meet client expectations. Our end-to-end game development services ensure high-quality and timely delivery of games."
        />{" "}
        <Slide
          name="Motion Graphics"
          img={motion}
          description="Our motion graphics team specializes in creating animated graphics and typography for videos, presentations, and websites. Our services include concept design, story boarding, asset creation, animation, and sound design."
        />
        <Slide
          name="Graphics Design"
          img={graphics}
          description="Our graphics design team specializes in creating high-quality and visually appealing designs for a wide range of applications, including branding, advertising, packaging, and digital media. We work closely with clients to bring their vision to life"
        />{" "}
        <Slide
          name="3D Modelling"
          img={threeD}
          description="Our 3D modeling team is highly skilled in creating realistic and detailed 3D models for film, television, and gaming industries. We offer services in character and prop modeling, environment and architectural visualization, and product design. Our team works closely with clients to deliver exceptional results."
        />      */}
      </div>{" "}
    </section>
  );
};

export default Services;
