import React, { useEffect } from "react";
import SectionHeader from "../Components/SectionHeader";
// import { register } from "swiper/element/bundle";

// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";
import Aos from "aos";
import "aos/dist/aos.css";

// import required modules
import {
  Keyboard,
  Scrollbar,
  Pagination,
  Autoplay,
  EffectFade,
} from "swiper/modules";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

// Import Images
import animation from "../images/animation-img.svg";
import graphics from "../images/graphics-img.svg";
import motion from "../images/motion-graphics-img.svg";
import threeD from "../images/3D-modelling-img.svg";
import vfx from "../images/vfx-img.svg";
import gameDev from "../images/game-dev-img.svg";

// Service Components dynamically generated by passing in props
const Slide = ({ name, img, description }) => {
  return (
    <figure className="flex flex-col items-center gap-[1.5rem] w-[45%]">
      <img src={img} alt={name} />
      <h3 className="font-bold text-3xl self-start">{name}</h3>
      <p>{description}</p>
    </figure>
  );
};

// Each frame for the slider containig two components
const SliderFrameOne = () => {
  return (
    <div className="flex gap-[5rem] w-[100%]">
      <Slide
        name="Animation"
        img={animation}
        description="Our animators specialize in 2D and 3D animation and are experienced in creating both character and motion graphics animations. Our animation services include concept design, storyboarding, character design, asset creation, and animation."
      />
      <Slide
        name="VFX"
        img={vfx}
        description="Our VFX team has extensive experience in creating realistic and seamless visual effects for film, television, and commercials. Our services include green screen removal, compositing, 3D tracking, particle simulations, and digital matte painting Etc"
      />
    </div>
  );
};

const SliderFrameTwo = () => {
  return (
    <div className="flex gap-[5rem] w-[100%]">
      <Slide
        name="Game Development"
        img={gameDev}
        description="Our game development team creates immersive games for desktop, mobile, and consoles. We specialize in concept design, game design, and artwork creation. We use industry-standard tools such as Unity and Unreal Engine to develop games that meet client expectations. Our end-to-end game development services ensure high-quality and timely delivery of games."
      />{" "}
      <Slide
        name="Motion Graphics"
        img={motion}
        description="Our motion graphics team specializes in creating animated graphics and typography for videos, presentations, and websites. Our services include concept design, storyboarding, asset creation, animation, and sound design."
      />
    </div>
  );
};

const SliderFrameThree = () => {
  return (
    <div className="flex gap-[5rem] w-[100%]">
      <Slide
        name="Graphics Design"
        om
        img={graphics}
        description="Our graphics design team specializes in creating high-quality and visually appealing designs for a wide range of applications, including branding, advertising, packaging, and digital media. We work closely with clients to bring their vision to life"
      />{" "}
      <Slide
        name="3D Modelling"
        img={threeD}
        description="Our 3D modeling team is highly skilled in creating realistic and detailed 3D models for film, television, and gaming industries. We offer services in character and prop modeling, environment and architectural visualization, and product design. Our team works closely with clients to deliver exceptional results."
      />
    </div>
  );
};

// Service section component containg the 3 slider frames
const Services = () => {
  useEffect(() => {
    Aos.init();
  }, []);

  return (
    <section id="services" className="bg-elPurple">
      <SectionHeader
        color={"elLilac"}
        section={"SERVICES"}
        heading={"Our team is proficient in the following areas"}
        animate={"zoom-out"}
      />
      <div className="py-[10rem] px-[5rem] text-white">
        <Swiper
          slidesPerView={1}
          spaceBetween={30}
          centeredSlides={false}
          slidesPerGroupSkip={2}
          grabCursor={false}
          keyboard={{
            enabled: true,
          }}
          effect={"true"}
          scrollbar={true}
          pagination={{
            clickable: true,
          }}
          autoplay={{
            delay: 3000,
            disableOnInteraction: false,
          }}
          modules={[Keyboard, EffectFade, Autoplay, Scrollbar, Pagination]}
          className="mySwiper"
        >
          <SwiperSlide className="swiper-wrapper flex">
            <SliderFrameOne />
          </SwiperSlide>{" "}
          <SwiperSlide className="swiper-wrapper flex">
            <SliderFrameTwo />
          </SwiperSlide>{" "}
          <SwiperSlide className="swiper-wrapper flex">
            <SliderFrameThree />
          </SwiperSlide>{" "}
        </Swiper>
      </div>
    </section>
  );
};

export default Services;
